version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: smartcook-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=123  # Mật khẩu SA 
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: